# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
resources:
  pipelines: 
  - pipeline: 'Release Build'
    source: 'Release Build'
    trigger: 
      branches:
        include: 
        - experiment*

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- download: Release Build
  artifact: 'drop'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'c1c94d09-2b2e-4e9b-ba55-eef019ef1a9b'
    pipeline: '89'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'